/**
 * wc/store
 * OpenAPI document of the namespace wc/store. Based on generated json document, with some changes and additions
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class CalculateAttributeCounts (
  /* Taxonomy name. */
  taxonomy: Option[String] = None,
  /* Query type being performed which may affect counts. Valid values include \"and\" and \"or\". */
  queryType: Option[CalculateAttributeCountsEnums.QueryType] = None
) extends ApiModel

object CalculateAttributeCountsEnums {

  type QueryType = QueryType.Value
  object QueryType extends Enumeration {
    val And = Value("and")
    val Or = Value("or")
  }

}
