/**
 * wc/store
 * Generated OpenAPI document of the namespace wc/store on Software-Creation.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class CartTotals3 (
  /* Currency code (in ISO format) for returned prices. */
  currencyCode: Option[String] = None,
  /* Currency symbol for the currency which can be used to format returned prices. */
  currencySymbol: Option[String] = None,
  /* Currency minor unit (number of digits after the decimal separator) for returned prices. */
  currencyMinorUnit: Option[Int] = None,
  /* Decimal separator for the currency which can be used to format returned prices. */
  currencyDecimalSeparator: Option[String] = None,
  /* Thousand separator for the currency which can be used to format returned prices. */
  currencyThousandSeparator: Option[String] = None,
  /* Price prefix for the currency which can be used to format returned prices. */
  currencyPrefix: Option[String] = None,
  /* Price prefix for the currency which can be used to format returned prices. */
  currencySuffix: Option[String] = None,
  /* Total price of items in the cart. */
  totalItems: Option[String] = None,
  /* Total tax on items in the cart. */
  totalItemsTax: Option[String] = None,
  /* Total price of any applied fees. */
  totalFees: Option[String] = None,
  /* Total tax on fees. */
  totalFeesTax: Option[String] = None,
  /* Total discount from applied coupons. */
  totalDiscount: Option[String] = None,
  /* Total tax removed due to discount from applied coupons. */
  totalDiscountTax: Option[String] = None,
  /* Total price of shipping. If shipping has not been calculated, a null response will be sent. */
  totalShipping: Option[String] = None,
  /* Total tax on shipping. If shipping has not been calculated, a null response will be sent. */
  totalShippingTax: Option[String] = None,
  /* Total price the customer will pay. */
  totalPrice: Option[String] = None,
  /* Total tax applied to items and shipping. */
  totalTax: Option[String] = None,
  /* Lines of taxes applied to items and shipping. */
  taxLines: Option[Seq[CartTotals3TaxLines]] = None
) extends ApiModel

