/**
 * wc/store
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class CartItemData (
  /* Naam van de metadata. */
  name: Option[String] = None,
  /* Waarde van de metadata. */
  value: Option[String] = None,
  /* Optioneel, hoe de metadata-waarde moet worden weergegeven aan de gebruiker. */
  display: Option[String] = None
) extends ApiModel

