/**
 * wc/store
 * OpenAPI document of the namespace wc/store. Based on generated json document, with some changes and additions
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class CheckoutPaymentResult (
  /* Status of the payment returned by the gateway. One of success, pending, failure, error. */
  paymentStatus: Option[String] = None,
  /* An array of data being returned from the payment gateway. */
  paymentDetails: Option[Seq[CheckoutPaymentResultPaymentDetails]] = None,
  /* A URL to redirect the customer after checkout. This could be, for example, a link to the payment processors website. */
  redirectUrl: Option[String] = None
) extends ApiModel

