/**
 * wc/store
 * Generated OpenAPI document of the namespace wc/store on Software-Creation.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import java.net.URI
import org.woocommerce.akkaclient.core.ApiModel

case class ProductReviewReviewerAvatarUrls (
  /* Avatar URL with image size of 24 pixels. */
  `24`: Option[URI] = None,
  /* Avatar URL with image size of 48 pixels. */
  `48`: Option[URI] = None,
  /* Avatar URL with image size of 96 pixels. */
  `96`: Option[URI] = None
) extends ApiModel

