/**
 * wc/store
 * Generated OpenAPI document of the namespace wc/store on Software-Creation.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class ProductAttributes (
  /* The attribute ID, or 0 if the attribute is not taxonomy based. */
  id: Option[Int] = None,
  /* The attribute name. */
  name: Option[String] = None,
  /* The attribute taxonomy, or null if the attribute is not taxonomy based. */
  taxonomy: Option[String] = None,
  /* True if this attribute is used by product variations. */
  hasVariations: Option[Boolean] = None,
  /* List of assigned attribute terms. */
  terms: Option[Seq[ProductTerms]] = None
) extends ApiModel

