/**
 * wc/store
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class ProductTerms (
  /* De term ID, of 0 als het attribuut geen globaal attribuut is. */
  id: Option[Int] = None,
  /* De term naam. */
  name: Option[String] = None,
  /* De term slug. */
  slug: Option[String] = None,
  /* Als dit een standaard attribuut is */
  default: Option[Boolean] = None
) extends ApiModel

