/**
 * wc/store
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class ShippingAddress3 (
  /* Voornaam */
  firstName: String,
  /* Achternaam */
  lastName: String,
  /* Bedrijf */
  company: String,
  /* Adres */
  address1: String,
  /* Appartement, suite, enz. */
  address2: String,
  /* Plaats */
  city: String,
  /* Staats-/provinciecode of naam van de staat, provincie, provincie of district. */
  state: String,
  /* Postcode */
  postcode: String,
  /* Land/regio-code in ISO 3166-1 alfa-2 format. */
  country: String,
  /* Telefoon */
  phone: String
) extends ApiModel

