/**
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class SystemStatus (
  environment: Option[SystemStatusEnvironment] = None,
  database: Option[SystemStatusDatabase] = None,
  /* Active plugins. */
  activePlugins: Option[Seq[String]] = None,
  /* Inactive plugins. */
  inactivePlugins: Option[Seq[String]] = None,
  /* Dropins & MU plugins. */
  dropinsMuPlugins: Option[Seq[String]] = None,
  theme: Option[SystemStatusTheme] = None,
  settings: Option[SystemStatusSettings] = None,
  security: Option[SystemStatusSecurity] = None,
  /* WooCommerce pages. */
  pages: Option[Seq[String]] = None,
  /* Total post count. */
  postTypeCounts: Option[Seq[String]] = None
) extends ApiModel

