/**
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import java.net.URI
import org.woocommerce.akkaclient.core.ApiModel

case class SystemStatusTheme (
  /* Theme name. */
  name: Option[String] = None,
  /* Theme version. */
  version: Option[String] = None,
  /* Latest version of theme. */
  versionLatest: Option[String] = None,
  /* Theme author URL. */
  authorUrl: Option[URI] = None,
  /* Is this theme a child theme? */
  isChildTheme: Option[Boolean] = None,
  /* Does the theme declare WooCommerce support? */
  hasWoocommerceSupport: Option[Boolean] = None,
  /* Does the theme have a woocommerce.php file? */
  hasWoocommerceFile: Option[Boolean] = None,
  /* Does this theme have outdated templates? */
  hasOutdatedTemplates: Option[Boolean] = None,
  /* Template overrides. */
  overrides: Option[Seq[String]] = None,
  /* Parent theme name. */
  parentName: Option[String] = None,
  /* Parent theme version. */
  parentVersion: Option[String] = None,
  /* Parent theme author URL. */
  parentAuthorUrl: Option[URI] = None
) extends ApiModel

