/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Batch20
 */
public class Batch20Test {
    private final Batch20 model = new Batch20();

    /**
     * Model tests for Batch20
     */
    @Test
    public void testBatch20() {
        // TODO: test Batch20
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'reviewer'
     */
    @Test
    public void reviewerTest() {
        // TODO: test reviewer
    }

    /**
     * Test the property 'reviewerEmail'
     */
    @Test
    public void reviewerEmailTest() {
        // TODO: test reviewerEmail
    }

    /**
     * Test the property 'review'
     */
    @Test
    public void reviewTest() {
        // TODO: test review
    }

    /**
     * Test the property 'rating'
     */
    @Test
    public void ratingTest() {
        // TODO: test rating
    }

}
