/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CouponsMetaData;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Batch1
 */
public class Batch1Test {
    private final Batch1 model = new Batch1();

    /**
     * Model tests for Batch1
     */
    @Test
    public void testBatch1() {
        // TODO: test Batch1
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'discountType'
     */
    @Test
    public void discountTypeTest() {
        // TODO: test discountType
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'dateExpires'
     */
    @Test
    public void dateExpiresTest() {
        // TODO: test dateExpires
    }

    /**
     * Test the property 'dateExpiresGmt'
     */
    @Test
    public void dateExpiresGmtTest() {
        // TODO: test dateExpiresGmt
    }

    /**
     * Test the property 'individualUse'
     */
    @Test
    public void individualUseTest() {
        // TODO: test individualUse
    }

    /**
     * Test the property 'productIds'
     */
    @Test
    public void productIdsTest() {
        // TODO: test productIds
    }

    /**
     * Test the property 'excludedProductIds'
     */
    @Test
    public void excludedProductIdsTest() {
        // TODO: test excludedProductIds
    }

    /**
     * Test the property 'usageLimit'
     */
    @Test
    public void usageLimitTest() {
        // TODO: test usageLimit
    }

    /**
     * Test the property 'usageLimitPerUser'
     */
    @Test
    public void usageLimitPerUserTest() {
        // TODO: test usageLimitPerUser
    }

    /**
     * Test the property 'limitUsageToXItems'
     */
    @Test
    public void limitUsageToXItemsTest() {
        // TODO: test limitUsageToXItems
    }

    /**
     * Test the property 'freeShipping'
     */
    @Test
    public void freeShippingTest() {
        // TODO: test freeShipping
    }

    /**
     * Test the property 'productCategories'
     */
    @Test
    public void productCategoriesTest() {
        // TODO: test productCategories
    }

    /**
     * Test the property 'excludedProductCategories'
     */
    @Test
    public void excludedProductCategoriesTest() {
        // TODO: test excludedProductCategories
    }

    /**
     * Test the property 'excludeSaleItems'
     */
    @Test
    public void excludeSaleItemsTest() {
        // TODO: test excludeSaleItems
    }

    /**
     * Test the property 'minimumAmount'
     */
    @Test
    public void minimumAmountTest() {
        // TODO: test minimumAmount
    }

    /**
     * Test the property 'maximumAmount'
     */
    @Test
    public void maximumAmountTest() {
        // TODO: test maximumAmount
    }

    /**
     * Test the property 'emailRestrictions'
     */
    @Test
    public void emailRestrictionsTest() {
        // TODO: test emailRestrictions
    }

    /**
     * Test the property 'metaData'
     */
    @Test
    public void metaDataTest() {
        // TODO: test metaData
    }

}
