/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CouponsMetaData;
import org.openapitools.client.model.OrdersBilling;
import org.openapitools.client.model.OrdersCouponLines;
import org.openapitools.client.model.OrdersFeeLines;
import org.openapitools.client.model.OrdersLineItems;
import org.openapitools.client.model.OrdersShipping;
import org.openapitools.client.model.OrdersShippingLines;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Batch8
 */
public class Batch8Test {
    private final Batch8 model = new Batch8();

    /**
     * Model tests for Batch8
     */
    @Test
    public void testBatch8() {
        // TODO: test Batch8
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    public void parentIdTest() {
        // TODO: test parentId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'customerNote'
     */
    @Test
    public void customerNoteTest() {
        // TODO: test customerNote
    }

    /**
     * Test the property 'billing'
     */
    @Test
    public void billingTest() {
        // TODO: test billing
    }

    /**
     * Test the property 'shipping'
     */
    @Test
    public void shippingTest() {
        // TODO: test shipping
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'paymentMethodTitle'
     */
    @Test
    public void paymentMethodTitleTest() {
        // TODO: test paymentMethodTitle
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'metaData'
     */
    @Test
    public void metaDataTest() {
        // TODO: test metaData
    }

    /**
     * Test the property 'lineItems'
     */
    @Test
    public void lineItemsTest() {
        // TODO: test lineItems
    }

    /**
     * Test the property 'shippingLines'
     */
    @Test
    public void shippingLinesTest() {
        // TODO: test shippingLines
    }

    /**
     * Test the property 'feeLines'
     */
    @Test
    public void feeLinesTest() {
        // TODO: test feeLines
    }

    /**
     * Test the property 'couponLines'
     */
    @Test
    public void couponLinesTest() {
        // TODO: test couponLines
    }

    /**
     * Test the property 'setPaid'
     */
    @Test
    public void setPaidTest() {
        // TODO: test setPaid
    }

}
