/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OrderNote1
 */
public class OrderNote1Test {
    private final OrderNote1 model = new OrderNote1();

    /**
     * Model tests for OrderNote1
     */
    @Test
    public void testOrderNote1() {
        // TODO: test OrderNote1
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'customerNote'
     */
    @Test
    public void customerNoteTest() {
        // TODO: test customerNote
    }

    /**
     * Test the property 'addedByUser'
     */
    @Test
    public void addedByUserTest() {
        // TODO: test addedByUser
    }

}
