/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CouponsMetaData;
import org.openapitools.client.model.ProductsAttributes;
import org.openapitools.client.model.ProductsCategories;
import org.openapitools.client.model.ProductsDefaultAttributes;
import org.openapitools.client.model.ProductsDimensions;
import org.openapitools.client.model.ProductsDownloads;
import org.openapitools.client.model.ProductsImages;
import org.openapitools.client.model.ProductsTags;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Product4
 */
public class Product4Test {
    private final Product4 model = new Product4();

    /**
     * Model tests for Product4
     */
    @Test
    public void testProduct4() {
        // TODO: test Product4
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateCreatedGmt'
     */
    @Test
    public void dateCreatedGmtTest() {
        // TODO: test dateCreatedGmt
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'featured'
     */
    @Test
    public void featuredTest() {
        // TODO: test featured
    }

    /**
     * Test the property 'catalogVisibility'
     */
    @Test
    public void catalogVisibilityTest() {
        // TODO: test catalogVisibility
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'shortDescription'
     */
    @Test
    public void shortDescriptionTest() {
        // TODO: test shortDescription
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'regularPrice'
     */
    @Test
    public void regularPriceTest() {
        // TODO: test regularPrice
    }

    /**
     * Test the property 'salePrice'
     */
    @Test
    public void salePriceTest() {
        // TODO: test salePrice
    }

    /**
     * Test the property 'dateOnSaleFrom'
     */
    @Test
    public void dateOnSaleFromTest() {
        // TODO: test dateOnSaleFrom
    }

    /**
     * Test the property 'dateOnSaleFromGmt'
     */
    @Test
    public void dateOnSaleFromGmtTest() {
        // TODO: test dateOnSaleFromGmt
    }

    /**
     * Test the property 'dateOnSaleTo'
     */
    @Test
    public void dateOnSaleToTest() {
        // TODO: test dateOnSaleTo
    }

    /**
     * Test the property 'dateOnSaleToGmt'
     */
    @Test
    public void dateOnSaleToGmtTest() {
        // TODO: test dateOnSaleToGmt
    }

    /**
     * Test the property 'virtual'
     */
    @Test
    public void virtualTest() {
        // TODO: test virtual
    }

    /**
     * Test the property 'downloadable'
     */
    @Test
    public void downloadableTest() {
        // TODO: test downloadable
    }

    /**
     * Test the property 'downloads'
     */
    @Test
    public void downloadsTest() {
        // TODO: test downloads
    }

    /**
     * Test the property 'downloadLimit'
     */
    @Test
    public void downloadLimitTest() {
        // TODO: test downloadLimit
    }

    /**
     * Test the property 'downloadExpiry'
     */
    @Test
    public void downloadExpiryTest() {
        // TODO: test downloadExpiry
    }

    /**
     * Test the property 'externalUrl'
     */
    @Test
    public void externalUrlTest() {
        // TODO: test externalUrl
    }

    /**
     * Test the property 'buttonText'
     */
    @Test
    public void buttonTextTest() {
        // TODO: test buttonText
    }

    /**
     * Test the property 'taxStatus'
     */
    @Test
    public void taxStatusTest() {
        // TODO: test taxStatus
    }

    /**
     * Test the property 'taxClass'
     */
    @Test
    public void taxClassTest() {
        // TODO: test taxClass
    }

    /**
     * Test the property 'manageStock'
     */
    @Test
    public void manageStockTest() {
        // TODO: test manageStock
    }

    /**
     * Test the property 'stockQuantity'
     */
    @Test
    public void stockQuantityTest() {
        // TODO: test stockQuantity
    }

    /**
     * Test the property 'stockStatus'
     */
    @Test
    public void stockStatusTest() {
        // TODO: test stockStatus
    }

    /**
     * Test the property 'backorders'
     */
    @Test
    public void backordersTest() {
        // TODO: test backorders
    }

    /**
     * Test the property 'lowStockAmount'
     */
    @Test
    public void lowStockAmountTest() {
        // TODO: test lowStockAmount
    }

    /**
     * Test the property 'soldIndividually'
     */
    @Test
    public void soldIndividuallyTest() {
        // TODO: test soldIndividually
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

    /**
     * Test the property 'dimensions'
     */
    @Test
    public void dimensionsTest() {
        // TODO: test dimensions
    }

    /**
     * Test the property 'shippingClass'
     */
    @Test
    public void shippingClassTest() {
        // TODO: test shippingClass
    }

    /**
     * Test the property 'reviewsAllowed'
     */
    @Test
    public void reviewsAllowedTest() {
        // TODO: test reviewsAllowed
    }

    /**
     * Test the property 'upsellIds'
     */
    @Test
    public void upsellIdsTest() {
        // TODO: test upsellIds
    }

    /**
     * Test the property 'crossSellIds'
     */
    @Test
    public void crossSellIdsTest() {
        // TODO: test crossSellIds
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    public void parentIdTest() {
        // TODO: test parentId
    }

    /**
     * Test the property 'purchaseNote'
     */
    @Test
    public void purchaseNoteTest() {
        // TODO: test purchaseNote
    }

    /**
     * Test the property 'categories'
     */
    @Test
    public void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'images'
     */
    @Test
    public void imagesTest() {
        // TODO: test images
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'defaultAttributes'
     */
    @Test
    public void defaultAttributesTest() {
        // TODO: test defaultAttributes
    }

    /**
     * Test the property 'menuOrder'
     */
    @Test
    public void menuOrderTest() {
        // TODO: test menuOrder
    }

    /**
     * Test the property 'metaData'
     */
    @Test
    public void metaDataTest() {
        // TODO: test metaData
    }

}
