/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProductReviewReviewerAvatarUrls
 */
public class ProductReviewReviewerAvatarUrlsTest {
    private final ProductReviewReviewerAvatarUrls model = new ProductReviewReviewerAvatarUrls();

    /**
     * Model tests for ProductReviewReviewerAvatarUrls
     */
    @Test
    public void testProductReviewReviewerAvatarUrls() {
        // TODO: test ProductReviewReviewerAvatarUrls
    }

    /**
     * Test the property '_24'
     */
    @Test
    public void _24Test() {
        // TODO: test _24
    }

    /**
     * Test the property '_48'
     */
    @Test
    public void _48Test() {
        // TODO: test _48
    }

    /**
     * Test the property '_96'
     */
    @Test
    public void _96Test() {
        // TODO: test _96
    }

}
