/**
 * wc/store
 * OpenAPI document of the namespace wc/store. Based on generated json document, with some changes and additions
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.sttpclient.model


  /**
   * Price data provided using the smallest unit of the currency.
   */
case class ProductPrices(
  /* Currency code (in ISO format) for returned prices. */
  currencyCode: Option[String] = None,
  /* Currency symbol for the currency which can be used to format returned prices. */
  currencySymbol: Option[String] = None,
  /* Currency minor unit (number of digits after the decimal separator) for returned prices. */
  currencyMinorUnit: Option[Int] = None,
  /* Decimal separator for the currency which can be used to format returned prices. */
  currencyDecimalSeparator: Option[String] = None,
  /* Thousand separator for the currency which can be used to format returned prices. */
  currencyThousandSeparator: Option[String] = None,
  /* Price prefix for the currency which can be used to format returned prices. */
  currencyPrefix: Option[String] = None,
  /* Price prefix for the currency which can be used to format returned prices. */
  currencySuffix: Option[String] = None,
  /* Current product price. */
  price: Option[String] = None,
  /* Regular product price. */
  regularPrice: Option[String] = None,
  /* Sale product price, if applicable. */
  salePrice: Option[String] = None,
  /* Price range, if applicable. */
  priceRange: Option[Any] = None
)

