/**
 * wc/store
 * OpenAPI document of the namespace wc/store. Based on generated json document, with some changes and additions
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.sttpclient.model


case class Term(
  /* Unique identifier for the resource. */
  id: Option[Int] = None,
  /* Term name. */
  name: Option[String] = None,
  /* String based identifier for the term. */
  slug: Option[String] = None,
  /* Term description. */
  description: Option[String] = None,
  /* Parent term ID, if applicable. */
  parent: Option[Int] = None,
  /* Number of objects (posts of any type) assigned to the term. */
  count: Option[Int] = None
)

