/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.CustomerDownloadFile;

/**
 * CustomerDownload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-03T11:14:37.017890013+01:00[Europe/Amsterdam]")
public class CustomerDownload {
  public static final String SERIALIZED_NAME_DOWNLOAD_ID = "download_id";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_ID)
  private String downloadId;

  public static final String SERIALIZED_NAME_DOWNLOAD_URL = "download_url";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_URL)
  private String downloadUrl;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "product_id";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  private Integer productId;

  public static final String SERIALIZED_NAME_PRODUCT_NAME = "product_name";
  @SerializedName(SERIALIZED_NAME_PRODUCT_NAME)
  private String productName;

  public static final String SERIALIZED_NAME_DOWNLOAD_NAME = "download_name";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_NAME)
  private String downloadName;

  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  private Integer orderId;

  public static final String SERIALIZED_NAME_ORDER_KEY = "order_key";
  @SerializedName(SERIALIZED_NAME_ORDER_KEY)
  private String orderKey;

  public static final String SERIALIZED_NAME_DOWNLOADS_REMAINING = "downloads_remaining";
  @SerializedName(SERIALIZED_NAME_DOWNLOADS_REMAINING)
  private String downloadsRemaining;

  public static final String SERIALIZED_NAME_ACCESS_EXPIRES = "access_expires";
  @SerializedName(SERIALIZED_NAME_ACCESS_EXPIRES)
  private String accessExpires;

  public static final String SERIALIZED_NAME_ACCESS_EXPIRES_GMT = "access_expires_gmt";
  @SerializedName(SERIALIZED_NAME_ACCESS_EXPIRES_GMT)
  private String accessExpiresGmt;

  public static final String SERIALIZED_NAME_FILE = "file";
  @SerializedName(SERIALIZED_NAME_FILE)
  private CustomerDownloadFile file;


  public CustomerDownload downloadId(String downloadId) {
    
    this.downloadId = downloadId;
    return this;
  }

   /**
   * Download ID.
   * @return downloadId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Download ID.")

  public String getDownloadId() {
    return downloadId;
  }


  public void setDownloadId(String downloadId) {
    this.downloadId = downloadId;
  }


  public CustomerDownload downloadUrl(String downloadUrl) {
    
    this.downloadUrl = downloadUrl;
    return this;
  }

   /**
   * Download file URL.
   * @return downloadUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Download file URL.")

  public String getDownloadUrl() {
    return downloadUrl;
  }


  public void setDownloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }


  public CustomerDownload productId(Integer productId) {
    
    this.productId = productId;
    return this;
  }

   /**
   * Downloadable product ID.
   * @return productId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Downloadable product ID.")

  public Integer getProductId() {
    return productId;
  }


  public void setProductId(Integer productId) {
    this.productId = productId;
  }


  public CustomerDownload productName(String productName) {
    
    this.productName = productName;
    return this;
  }

   /**
   * Product name.
   * @return productName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Product name.")

  public String getProductName() {
    return productName;
  }


  public void setProductName(String productName) {
    this.productName = productName;
  }


  public CustomerDownload downloadName(String downloadName) {
    
    this.downloadName = downloadName;
    return this;
  }

   /**
   * Downloadable file name.
   * @return downloadName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Downloadable file name.")

  public String getDownloadName() {
    return downloadName;
  }


  public void setDownloadName(String downloadName) {
    this.downloadName = downloadName;
  }


  public CustomerDownload orderId(Integer orderId) {
    
    this.orderId = orderId;
    return this;
  }

   /**
   * Order ID.
   * @return orderId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Order ID.")

  public Integer getOrderId() {
    return orderId;
  }


  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }


  public CustomerDownload orderKey(String orderKey) {
    
    this.orderKey = orderKey;
    return this;
  }

   /**
   * Order key.
   * @return orderKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Order key.")

  public String getOrderKey() {
    return orderKey;
  }


  public void setOrderKey(String orderKey) {
    this.orderKey = orderKey;
  }


  public CustomerDownload downloadsRemaining(String downloadsRemaining) {
    
    this.downloadsRemaining = downloadsRemaining;
    return this;
  }

   /**
   * Number of downloads remaining.
   * @return downloadsRemaining
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number of downloads remaining.")

  public String getDownloadsRemaining() {
    return downloadsRemaining;
  }


  public void setDownloadsRemaining(String downloadsRemaining) {
    this.downloadsRemaining = downloadsRemaining;
  }


  public CustomerDownload accessExpires(String accessExpires) {
    
    this.accessExpires = accessExpires;
    return this;
  }

   /**
   * The date when download access expires, in the site&#39;s timezone.
   * @return accessExpires
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date when download access expires, in the site's timezone.")

  public String getAccessExpires() {
    return accessExpires;
  }


  public void setAccessExpires(String accessExpires) {
    this.accessExpires = accessExpires;
  }


  public CustomerDownload accessExpiresGmt(String accessExpiresGmt) {
    
    this.accessExpiresGmt = accessExpiresGmt;
    return this;
  }

   /**
   * The date when download access expires, as GMT.
   * @return accessExpiresGmt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date when download access expires, as GMT.")

  public String getAccessExpiresGmt() {
    return accessExpiresGmt;
  }


  public void setAccessExpiresGmt(String accessExpiresGmt) {
    this.accessExpiresGmt = accessExpiresGmt;
  }


  public CustomerDownload file(CustomerDownloadFile file) {
    
    this.file = file;
    return this;
  }

   /**
   * Get file
   * @return file
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CustomerDownloadFile getFile() {
    return file;
  }


  public void setFile(CustomerDownloadFile file) {
    this.file = file;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerDownload customerDownload = (CustomerDownload) o;
    return Objects.equals(this.downloadId, customerDownload.downloadId) &&
        Objects.equals(this.downloadUrl, customerDownload.downloadUrl) &&
        Objects.equals(this.productId, customerDownload.productId) &&
        Objects.equals(this.productName, customerDownload.productName) &&
        Objects.equals(this.downloadName, customerDownload.downloadName) &&
        Objects.equals(this.orderId, customerDownload.orderId) &&
        Objects.equals(this.orderKey, customerDownload.orderKey) &&
        Objects.equals(this.downloadsRemaining, customerDownload.downloadsRemaining) &&
        Objects.equals(this.accessExpires, customerDownload.accessExpires) &&
        Objects.equals(this.accessExpiresGmt, customerDownload.accessExpiresGmt) &&
        Objects.equals(this.file, customerDownload.file);
  }

  @Override
  public int hashCode() {
    return Objects.hash(downloadId, downloadUrl, productId, productName, downloadName, orderId, orderKey, downloadsRemaining, accessExpires, accessExpiresGmt, file);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerDownload {\n");
    sb.append("    downloadId: ").append(toIndentedString(downloadId)).append("\n");
    sb.append("    downloadUrl: ").append(toIndentedString(downloadUrl)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    downloadName: ").append(toIndentedString(downloadName)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderKey: ").append(toIndentedString(orderKey)).append("\n");
    sb.append("    downloadsRemaining: ").append(toIndentedString(downloadsRemaining)).append("\n");
    sb.append("    accessExpires: ").append(toIndentedString(accessExpires)).append("\n");
    sb.append("    accessExpiresGmt: ").append(toIndentedString(accessExpiresGmt)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

