/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CouponsMetaData;

/**
 * OrdersCouponLines
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-03T11:14:37.017890013+01:00[Europe/Amsterdam]")
public class OrdersCouponLines {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_DISCOUNT = "discount";
  @SerializedName(SERIALIZED_NAME_DISCOUNT)
  private String discount;

  public static final String SERIALIZED_NAME_DISCOUNT_TAX = "discount_tax";
  @SerializedName(SERIALIZED_NAME_DISCOUNT_TAX)
  private String discountTax;

  public static final String SERIALIZED_NAME_META_DATA = "meta_data";
  @SerializedName(SERIALIZED_NAME_META_DATA)
  private List<CouponsMetaData> metaData = null;


  public OrdersCouponLines id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Item ID.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Item ID.")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public OrdersCouponLines code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Coupon code.
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Coupon code.")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public OrdersCouponLines discount(String discount) {
    
    this.discount = discount;
    return this;
  }

   /**
   * Discount total.
   * @return discount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Discount total.")

  public String getDiscount() {
    return discount;
  }


  public void setDiscount(String discount) {
    this.discount = discount;
  }


  public OrdersCouponLines discountTax(String discountTax) {
    
    this.discountTax = discountTax;
    return this;
  }

   /**
   * Discount total tax.
   * @return discountTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Discount total tax.")

  public String getDiscountTax() {
    return discountTax;
  }


  public void setDiscountTax(String discountTax) {
    this.discountTax = discountTax;
  }


  public OrdersCouponLines metaData(List<CouponsMetaData> metaData) {
    
    this.metaData = metaData;
    return this;
  }

  public OrdersCouponLines addMetaDataItem(CouponsMetaData metaDataItem) {
    if (this.metaData == null) {
      this.metaData = new ArrayList<CouponsMetaData>();
    }
    this.metaData.add(metaDataItem);
    return this;
  }

   /**
   * Meta data.
   * @return metaData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Meta data.")

  public List<CouponsMetaData> getMetaData() {
    return metaData;
  }


  public void setMetaData(List<CouponsMetaData> metaData) {
    this.metaData = metaData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrdersCouponLines ordersCouponLines = (OrdersCouponLines) o;
    return Objects.equals(this.id, ordersCouponLines.id) &&
        Objects.equals(this.code, ordersCouponLines.code) &&
        Objects.equals(this.discount, ordersCouponLines.discount) &&
        Objects.equals(this.discountTax, ordersCouponLines.discountTax) &&
        Objects.equals(this.metaData, ordersCouponLines.metaData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, code, discount, discountTax, metaData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrdersCouponLines {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    discountTax: ").append(toIndentedString(discountTax)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

