/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OrdersMetaData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-03T11:14:37.017890013+01:00[Europe/Amsterdam]")
public class OrdersMetaData {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_DISPLAY_KEY = "display_key";
  @SerializedName(SERIALIZED_NAME_DISPLAY_KEY)
  private String displayKey;

  public static final String SERIALIZED_NAME_DISPLAY_VALUE = "display_value";
  @SerializedName(SERIALIZED_NAME_DISPLAY_VALUE)
  private String displayValue;


  public OrdersMetaData id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Meta ID.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Meta ID.")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public OrdersMetaData key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * Meta key.
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Meta key.")

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public OrdersMetaData value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Meta value.
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Meta value.")

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  public OrdersMetaData displayKey(String displayKey) {
    
    this.displayKey = displayKey;
    return this;
  }

   /**
   * Meta key for UI display.
   * @return displayKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Meta key for UI display.")

  public String getDisplayKey() {
    return displayKey;
  }


  public void setDisplayKey(String displayKey) {
    this.displayKey = displayKey;
  }


  public OrdersMetaData displayValue(String displayValue) {
    
    this.displayValue = displayValue;
    return this;
  }

   /**
   * Meta value for UI display.
   * @return displayValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Meta value for UI display.")

  public String getDisplayValue() {
    return displayValue;
  }


  public void setDisplayValue(String displayValue) {
    this.displayValue = displayValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrdersMetaData ordersMetaData = (OrdersMetaData) o;
    return Objects.equals(this.id, ordersMetaData.id) &&
        Objects.equals(this.key, ordersMetaData.key) &&
        Objects.equals(this.value, ordersMetaData.value) &&
        Objects.equals(this.displayKey, ordersMetaData.displayKey) &&
        Objects.equals(this.displayValue, ordersMetaData.displayValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, key, value, displayKey, displayValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrdersMetaData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    displayKey: ").append(toIndentedString(displayKey)).append("\n");
    sb.append("    displayValue: ").append(toIndentedString(displayValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

