/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ProductsDefaultAttributes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-03T11:14:37.017890013+01:00[Europe/Amsterdam]")
public class ProductsDefaultAttributes {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_OPTION = "option";
  @SerializedName(SERIALIZED_NAME_OPTION)
  private String option;


  public ProductsDefaultAttributes id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Attribute ID.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Attribute ID.")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public ProductsDefaultAttributes name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Attribute name.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Attribute name.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ProductsDefaultAttributes option(String option) {
    
    this.option = option;
    return this;
  }

   /**
   * Selected attribute term name.
   * @return option
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Selected attribute term name.")

  public String getOption() {
    return option;
  }


  public void setOption(String option) {
    this.option = option;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductsDefaultAttributes productsDefaultAttributes = (ProductsDefaultAttributes) o;
    return Objects.equals(this.id, productsDefaultAttributes.id) &&
        Objects.equals(this.name, productsDefaultAttributes.name) &&
        Objects.equals(this.option, productsDefaultAttributes.option);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, option);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductsDefaultAttributes {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    option: ").append(toIndentedString(option)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

