/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SalesReport
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-03T11:14:37.017890013+01:00[Europe/Amsterdam]")
public class SalesReport {
  public static final String SERIALIZED_NAME_TOTAL_SALES = "total_sales";
  @SerializedName(SERIALIZED_NAME_TOTAL_SALES)
  private String totalSales;

  public static final String SERIALIZED_NAME_NET_SALES = "net_sales";
  @SerializedName(SERIALIZED_NAME_NET_SALES)
  private String netSales;

  public static final String SERIALIZED_NAME_AVERAGE_SALES = "average_sales";
  @SerializedName(SERIALIZED_NAME_AVERAGE_SALES)
  private String averageSales;

  public static final String SERIALIZED_NAME_TOTAL_ORDERS = "total_orders";
  @SerializedName(SERIALIZED_NAME_TOTAL_ORDERS)
  private Integer totalOrders;

  public static final String SERIALIZED_NAME_TOTAL_ITEMS = "total_items";
  @SerializedName(SERIALIZED_NAME_TOTAL_ITEMS)
  private Integer totalItems;

  public static final String SERIALIZED_NAME_TOTAL_TAX = "total_tax";
  @SerializedName(SERIALIZED_NAME_TOTAL_TAX)
  private String totalTax;

  public static final String SERIALIZED_NAME_TOTAL_SHIPPING = "total_shipping";
  @SerializedName(SERIALIZED_NAME_TOTAL_SHIPPING)
  private String totalShipping;

  public static final String SERIALIZED_NAME_TOTAL_REFUNDS = "total_refunds";
  @SerializedName(SERIALIZED_NAME_TOTAL_REFUNDS)
  private Integer totalRefunds;

  public static final String SERIALIZED_NAME_TOTAL_DISCOUNT = "total_discount";
  @SerializedName(SERIALIZED_NAME_TOTAL_DISCOUNT)
  private Integer totalDiscount;

  public static final String SERIALIZED_NAME_TOTALS_GROUPED_BY = "totals_grouped_by";
  @SerializedName(SERIALIZED_NAME_TOTALS_GROUPED_BY)
  private String totalsGroupedBy;

  public static final String SERIALIZED_NAME_TOTALS = "totals";
  @SerializedName(SERIALIZED_NAME_TOTALS)
  private List<Integer> totals = null;


  public SalesReport totalSales(String totalSales) {
    
    this.totalSales = totalSales;
    return this;
  }

   /**
   * Gross sales in the period.
   * @return totalSales
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Gross sales in the period.")

  public String getTotalSales() {
    return totalSales;
  }


  public void setTotalSales(String totalSales) {
    this.totalSales = totalSales;
  }


  public SalesReport netSales(String netSales) {
    
    this.netSales = netSales;
    return this;
  }

   /**
   * Net sales in the period.
   * @return netSales
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Net sales in the period.")

  public String getNetSales() {
    return netSales;
  }


  public void setNetSales(String netSales) {
    this.netSales = netSales;
  }


  public SalesReport averageSales(String averageSales) {
    
    this.averageSales = averageSales;
    return this;
  }

   /**
   * Average net daily sales.
   * @return averageSales
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Average net daily sales.")

  public String getAverageSales() {
    return averageSales;
  }


  public void setAverageSales(String averageSales) {
    this.averageSales = averageSales;
  }


  public SalesReport totalOrders(Integer totalOrders) {
    
    this.totalOrders = totalOrders;
    return this;
  }

   /**
   * Total of orders placed.
   * @return totalOrders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total of orders placed.")

  public Integer getTotalOrders() {
    return totalOrders;
  }


  public void setTotalOrders(Integer totalOrders) {
    this.totalOrders = totalOrders;
  }


  public SalesReport totalItems(Integer totalItems) {
    
    this.totalItems = totalItems;
    return this;
  }

   /**
   * Total of items purchased.
   * @return totalItems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total of items purchased.")

  public Integer getTotalItems() {
    return totalItems;
  }


  public void setTotalItems(Integer totalItems) {
    this.totalItems = totalItems;
  }


  public SalesReport totalTax(String totalTax) {
    
    this.totalTax = totalTax;
    return this;
  }

   /**
   * Total charged for taxes.
   * @return totalTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total charged for taxes.")

  public String getTotalTax() {
    return totalTax;
  }


  public void setTotalTax(String totalTax) {
    this.totalTax = totalTax;
  }


  public SalesReport totalShipping(String totalShipping) {
    
    this.totalShipping = totalShipping;
    return this;
  }

   /**
   * Total charged for shipping.
   * @return totalShipping
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total charged for shipping.")

  public String getTotalShipping() {
    return totalShipping;
  }


  public void setTotalShipping(String totalShipping) {
    this.totalShipping = totalShipping;
  }


  public SalesReport totalRefunds(Integer totalRefunds) {
    
    this.totalRefunds = totalRefunds;
    return this;
  }

   /**
   * Total of refunded orders.
   * @return totalRefunds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total of refunded orders.")

  public Integer getTotalRefunds() {
    return totalRefunds;
  }


  public void setTotalRefunds(Integer totalRefunds) {
    this.totalRefunds = totalRefunds;
  }


  public SalesReport totalDiscount(Integer totalDiscount) {
    
    this.totalDiscount = totalDiscount;
    return this;
  }

   /**
   * Total of coupons used.
   * @return totalDiscount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total of coupons used.")

  public Integer getTotalDiscount() {
    return totalDiscount;
  }


  public void setTotalDiscount(Integer totalDiscount) {
    this.totalDiscount = totalDiscount;
  }


  public SalesReport totalsGroupedBy(String totalsGroupedBy) {
    
    this.totalsGroupedBy = totalsGroupedBy;
    return this;
  }

   /**
   * Group type.
   * @return totalsGroupedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Group type.")

  public String getTotalsGroupedBy() {
    return totalsGroupedBy;
  }


  public void setTotalsGroupedBy(String totalsGroupedBy) {
    this.totalsGroupedBy = totalsGroupedBy;
  }


  public SalesReport totals(List<Integer> totals) {
    
    this.totals = totals;
    return this;
  }

  public SalesReport addTotalsItem(Integer totalsItem) {
    if (this.totals == null) {
      this.totals = new ArrayList<Integer>();
    }
    this.totals.add(totalsItem);
    return this;
  }

   /**
   * Totals.
   * @return totals
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Totals.")

  public List<Integer> getTotals() {
    return totals;
  }


  public void setTotals(List<Integer> totals) {
    this.totals = totals;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalesReport salesReport = (SalesReport) o;
    return Objects.equals(this.totalSales, salesReport.totalSales) &&
        Objects.equals(this.netSales, salesReport.netSales) &&
        Objects.equals(this.averageSales, salesReport.averageSales) &&
        Objects.equals(this.totalOrders, salesReport.totalOrders) &&
        Objects.equals(this.totalItems, salesReport.totalItems) &&
        Objects.equals(this.totalTax, salesReport.totalTax) &&
        Objects.equals(this.totalShipping, salesReport.totalShipping) &&
        Objects.equals(this.totalRefunds, salesReport.totalRefunds) &&
        Objects.equals(this.totalDiscount, salesReport.totalDiscount) &&
        Objects.equals(this.totalsGroupedBy, salesReport.totalsGroupedBy) &&
        Objects.equals(this.totals, salesReport.totals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalSales, netSales, averageSales, totalOrders, totalItems, totalTax, totalShipping, totalRefunds, totalDiscount, totalsGroupedBy, totals);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalesReport {\n");
    sb.append("    totalSales: ").append(toIndentedString(totalSales)).append("\n");
    sb.append("    netSales: ").append(toIndentedString(netSales)).append("\n");
    sb.append("    averageSales: ").append(toIndentedString(averageSales)).append("\n");
    sb.append("    totalOrders: ").append(toIndentedString(totalOrders)).append("\n");
    sb.append("    totalItems: ").append(toIndentedString(totalItems)).append("\n");
    sb.append("    totalTax: ").append(toIndentedString(totalTax)).append("\n");
    sb.append("    totalShipping: ").append(toIndentedString(totalShipping)).append("\n");
    sb.append("    totalRefunds: ").append(toIndentedString(totalRefunds)).append("\n");
    sb.append("    totalDiscount: ").append(toIndentedString(totalDiscount)).append("\n");
    sb.append("    totalsGroupedBy: ").append(toIndentedString(totalsGroupedBy)).append("\n");
    sb.append("    totals: ").append(toIndentedString(totals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

