/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CouponsMetaData;
import org.openapitools.client.model.ShopOrderRefundTaxes;

/**
 * ShopOrderRefundLineItems
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-03T11:14:37.017890013+01:00[Europe/Amsterdam]")
public class ShopOrderRefundLineItems {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "product_id";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  private String productId;

  public static final String SERIALIZED_NAME_VARIATION_ID = "variation_id";
  @SerializedName(SERIALIZED_NAME_VARIATION_ID)
  private Integer variationId;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private Integer quantity;

  public static final String SERIALIZED_NAME_TAX_CLASS = "tax_class";
  @SerializedName(SERIALIZED_NAME_TAX_CLASS)
  private String taxClass;

  public static final String SERIALIZED_NAME_SUBTOTAL = "subtotal";
  @SerializedName(SERIALIZED_NAME_SUBTOTAL)
  private String subtotal;

  public static final String SERIALIZED_NAME_SUBTOTAL_TAX = "subtotal_tax";
  @SerializedName(SERIALIZED_NAME_SUBTOTAL_TAX)
  private String subtotalTax;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private String total;

  public static final String SERIALIZED_NAME_TOTAL_TAX = "total_tax";
  @SerializedName(SERIALIZED_NAME_TOTAL_TAX)
  private String totalTax;

  public static final String SERIALIZED_NAME_TAXES = "taxes";
  @SerializedName(SERIALIZED_NAME_TAXES)
  private List<ShopOrderRefundTaxes> taxes = null;

  public static final String SERIALIZED_NAME_META_DATA = "meta_data";
  @SerializedName(SERIALIZED_NAME_META_DATA)
  private List<CouponsMetaData> metaData = null;

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  private String sku;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private BigDecimal price;

  public static final String SERIALIZED_NAME_REFUND_TOTAL = "refund_total";
  @SerializedName(SERIALIZED_NAME_REFUND_TOTAL)
  private BigDecimal refundTotal;


  public ShopOrderRefundLineItems id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Item ID.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Item ID.")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public ShopOrderRefundLineItems name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Product name.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Product name.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ShopOrderRefundLineItems productId(String productId) {
    
    this.productId = productId;
    return this;
  }

   /**
   * Product ID.
   * @return productId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Product ID.")

  public String getProductId() {
    return productId;
  }


  public void setProductId(String productId) {
    this.productId = productId;
  }


  public ShopOrderRefundLineItems variationId(Integer variationId) {
    
    this.variationId = variationId;
    return this;
  }

   /**
   * Variation ID, if applicable.
   * @return variationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Variation ID, if applicable.")

  public Integer getVariationId() {
    return variationId;
  }


  public void setVariationId(Integer variationId) {
    this.variationId = variationId;
  }


  public ShopOrderRefundLineItems quantity(Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * Quantity ordered.
   * @return quantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Quantity ordered.")

  public Integer getQuantity() {
    return quantity;
  }


  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  public ShopOrderRefundLineItems taxClass(String taxClass) {
    
    this.taxClass = taxClass;
    return this;
  }

   /**
   * Tax class of product.
   * @return taxClass
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Tax class of product.")

  public String getTaxClass() {
    return taxClass;
  }


  public void setTaxClass(String taxClass) {
    this.taxClass = taxClass;
  }


  public ShopOrderRefundLineItems subtotal(String subtotal) {
    
    this.subtotal = subtotal;
    return this;
  }

   /**
   * Line subtotal (before discounts).
   * @return subtotal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Line subtotal (before discounts).")

  public String getSubtotal() {
    return subtotal;
  }


  public void setSubtotal(String subtotal) {
    this.subtotal = subtotal;
  }


  public ShopOrderRefundLineItems subtotalTax(String subtotalTax) {
    
    this.subtotalTax = subtotalTax;
    return this;
  }

   /**
   * Line subtotal tax (before discounts).
   * @return subtotalTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Line subtotal tax (before discounts).")

  public String getSubtotalTax() {
    return subtotalTax;
  }


  public void setSubtotalTax(String subtotalTax) {
    this.subtotalTax = subtotalTax;
  }


  public ShopOrderRefundLineItems total(String total) {
    
    this.total = total;
    return this;
  }

   /**
   * Line total (after discounts).
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Line total (after discounts).")

  public String getTotal() {
    return total;
  }


  public void setTotal(String total) {
    this.total = total;
  }


  public ShopOrderRefundLineItems totalTax(String totalTax) {
    
    this.totalTax = totalTax;
    return this;
  }

   /**
   * Line total tax (after discounts).
   * @return totalTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Line total tax (after discounts).")

  public String getTotalTax() {
    return totalTax;
  }


  public void setTotalTax(String totalTax) {
    this.totalTax = totalTax;
  }


  public ShopOrderRefundLineItems taxes(List<ShopOrderRefundTaxes> taxes) {
    
    this.taxes = taxes;
    return this;
  }

  public ShopOrderRefundLineItems addTaxesItem(ShopOrderRefundTaxes taxesItem) {
    if (this.taxes == null) {
      this.taxes = new ArrayList<ShopOrderRefundTaxes>();
    }
    this.taxes.add(taxesItem);
    return this;
  }

   /**
   * Line taxes.
   * @return taxes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Line taxes.")

  public List<ShopOrderRefundTaxes> getTaxes() {
    return taxes;
  }


  public void setTaxes(List<ShopOrderRefundTaxes> taxes) {
    this.taxes = taxes;
  }


  public ShopOrderRefundLineItems metaData(List<CouponsMetaData> metaData) {
    
    this.metaData = metaData;
    return this;
  }

  public ShopOrderRefundLineItems addMetaDataItem(CouponsMetaData metaDataItem) {
    if (this.metaData == null) {
      this.metaData = new ArrayList<CouponsMetaData>();
    }
    this.metaData.add(metaDataItem);
    return this;
  }

   /**
   * Meta data.
   * @return metaData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Meta data.")

  public List<CouponsMetaData> getMetaData() {
    return metaData;
  }


  public void setMetaData(List<CouponsMetaData> metaData) {
    this.metaData = metaData;
  }


  public ShopOrderRefundLineItems sku(String sku) {
    
    this.sku = sku;
    return this;
  }

   /**
   * Product SKU.
   * @return sku
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Product SKU.")

  public String getSku() {
    return sku;
  }


  public void setSku(String sku) {
    this.sku = sku;
  }


  public ShopOrderRefundLineItems price(BigDecimal price) {
    
    this.price = price;
    return this;
  }

   /**
   * Product price.
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Product price.")

  public BigDecimal getPrice() {
    return price;
  }


  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  public ShopOrderRefundLineItems refundTotal(BigDecimal refundTotal) {
    
    this.refundTotal = refundTotal;
    return this;
  }

   /**
   * Amount that will be refunded for this line item (excluding taxes).
   * @return refundTotal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Amount that will be refunded for this line item (excluding taxes).")

  public BigDecimal getRefundTotal() {
    return refundTotal;
  }


  public void setRefundTotal(BigDecimal refundTotal) {
    this.refundTotal = refundTotal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopOrderRefundLineItems shopOrderRefundLineItems = (ShopOrderRefundLineItems) o;
    return Objects.equals(this.id, shopOrderRefundLineItems.id) &&
        Objects.equals(this.name, shopOrderRefundLineItems.name) &&
        Objects.equals(this.productId, shopOrderRefundLineItems.productId) &&
        Objects.equals(this.variationId, shopOrderRefundLineItems.variationId) &&
        Objects.equals(this.quantity, shopOrderRefundLineItems.quantity) &&
        Objects.equals(this.taxClass, shopOrderRefundLineItems.taxClass) &&
        Objects.equals(this.subtotal, shopOrderRefundLineItems.subtotal) &&
        Objects.equals(this.subtotalTax, shopOrderRefundLineItems.subtotalTax) &&
        Objects.equals(this.total, shopOrderRefundLineItems.total) &&
        Objects.equals(this.totalTax, shopOrderRefundLineItems.totalTax) &&
        Objects.equals(this.taxes, shopOrderRefundLineItems.taxes) &&
        Objects.equals(this.metaData, shopOrderRefundLineItems.metaData) &&
        Objects.equals(this.sku, shopOrderRefundLineItems.sku) &&
        Objects.equals(this.price, shopOrderRefundLineItems.price) &&
        Objects.equals(this.refundTotal, shopOrderRefundLineItems.refundTotal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, productId, variationId, quantity, taxClass, subtotal, subtotalTax, total, totalTax, taxes, metaData, sku, price, refundTotal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopOrderRefundLineItems {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    variationId: ").append(toIndentedString(variationId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    taxClass: ").append(toIndentedString(taxClass)).append("\n");
    sb.append("    subtotal: ").append(toIndentedString(subtotal)).append("\n");
    sb.append("    subtotalTax: ").append(toIndentedString(subtotalTax)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    totalTax: ").append(toIndentedString(totalTax)).append("\n");
    sb.append("    taxes: ").append(toIndentedString(taxes)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    refundTotal: ").append(toIndentedString(refundTotal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

