/*
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.SystemStatusDatabase;
import org.openapitools.client.model.SystemStatusEnvironment;
import org.openapitools.client.model.SystemStatusSecurity;
import org.openapitools.client.model.SystemStatusSettings;
import org.openapitools.client.model.SystemStatusTheme;

/**
 * SystemStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-03T11:14:37.017890013+01:00[Europe/Amsterdam]")
public class SystemStatus {
  public static final String SERIALIZED_NAME_ENVIRONMENT = "environment";
  @SerializedName(SERIALIZED_NAME_ENVIRONMENT)
  private SystemStatusEnvironment environment;

  public static final String SERIALIZED_NAME_DATABASE = "database";
  @SerializedName(SERIALIZED_NAME_DATABASE)
  private SystemStatusDatabase database;

  public static final String SERIALIZED_NAME_ACTIVE_PLUGINS = "active_plugins";
  @SerializedName(SERIALIZED_NAME_ACTIVE_PLUGINS)
  private List<String> activePlugins = null;

  public static final String SERIALIZED_NAME_INACTIVE_PLUGINS = "inactive_plugins";
  @SerializedName(SERIALIZED_NAME_INACTIVE_PLUGINS)
  private List<String> inactivePlugins = null;

  public static final String SERIALIZED_NAME_DROPINS_MU_PLUGINS = "dropins_mu_plugins";
  @SerializedName(SERIALIZED_NAME_DROPINS_MU_PLUGINS)
  private List<String> dropinsMuPlugins = null;

  public static final String SERIALIZED_NAME_THEME = "theme";
  @SerializedName(SERIALIZED_NAME_THEME)
  private SystemStatusTheme theme;

  public static final String SERIALIZED_NAME_SETTINGS = "settings";
  @SerializedName(SERIALIZED_NAME_SETTINGS)
  private SystemStatusSettings settings;

  public static final String SERIALIZED_NAME_SECURITY = "security";
  @SerializedName(SERIALIZED_NAME_SECURITY)
  private SystemStatusSecurity security;

  public static final String SERIALIZED_NAME_PAGES = "pages";
  @SerializedName(SERIALIZED_NAME_PAGES)
  private List<String> pages = null;

  public static final String SERIALIZED_NAME_POST_TYPE_COUNTS = "post_type_counts";
  @SerializedName(SERIALIZED_NAME_POST_TYPE_COUNTS)
  private List<String> postTypeCounts = null;


  public SystemStatus environment(SystemStatusEnvironment environment) {
    
    this.environment = environment;
    return this;
  }

   /**
   * Get environment
   * @return environment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SystemStatusEnvironment getEnvironment() {
    return environment;
  }


  public void setEnvironment(SystemStatusEnvironment environment) {
    this.environment = environment;
  }


  public SystemStatus database(SystemStatusDatabase database) {
    
    this.database = database;
    return this;
  }

   /**
   * Get database
   * @return database
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SystemStatusDatabase getDatabase() {
    return database;
  }


  public void setDatabase(SystemStatusDatabase database) {
    this.database = database;
  }


  public SystemStatus activePlugins(List<String> activePlugins) {
    
    this.activePlugins = activePlugins;
    return this;
  }

  public SystemStatus addActivePluginsItem(String activePluginsItem) {
    if (this.activePlugins == null) {
      this.activePlugins = new ArrayList<String>();
    }
    this.activePlugins.add(activePluginsItem);
    return this;
  }

   /**
   * Active plugins.
   * @return activePlugins
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Active plugins.")

  public List<String> getActivePlugins() {
    return activePlugins;
  }


  public void setActivePlugins(List<String> activePlugins) {
    this.activePlugins = activePlugins;
  }


  public SystemStatus inactivePlugins(List<String> inactivePlugins) {
    
    this.inactivePlugins = inactivePlugins;
    return this;
  }

  public SystemStatus addInactivePluginsItem(String inactivePluginsItem) {
    if (this.inactivePlugins == null) {
      this.inactivePlugins = new ArrayList<String>();
    }
    this.inactivePlugins.add(inactivePluginsItem);
    return this;
  }

   /**
   * Inactive plugins.
   * @return inactivePlugins
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Inactive plugins.")

  public List<String> getInactivePlugins() {
    return inactivePlugins;
  }


  public void setInactivePlugins(List<String> inactivePlugins) {
    this.inactivePlugins = inactivePlugins;
  }


  public SystemStatus dropinsMuPlugins(List<String> dropinsMuPlugins) {
    
    this.dropinsMuPlugins = dropinsMuPlugins;
    return this;
  }

  public SystemStatus addDropinsMuPluginsItem(String dropinsMuPluginsItem) {
    if (this.dropinsMuPlugins == null) {
      this.dropinsMuPlugins = new ArrayList<String>();
    }
    this.dropinsMuPlugins.add(dropinsMuPluginsItem);
    return this;
  }

   /**
   * Dropins &amp; MU plugins.
   * @return dropinsMuPlugins
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Dropins & MU plugins.")

  public List<String> getDropinsMuPlugins() {
    return dropinsMuPlugins;
  }


  public void setDropinsMuPlugins(List<String> dropinsMuPlugins) {
    this.dropinsMuPlugins = dropinsMuPlugins;
  }


  public SystemStatus theme(SystemStatusTheme theme) {
    
    this.theme = theme;
    return this;
  }

   /**
   * Get theme
   * @return theme
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SystemStatusTheme getTheme() {
    return theme;
  }


  public void setTheme(SystemStatusTheme theme) {
    this.theme = theme;
  }


  public SystemStatus settings(SystemStatusSettings settings) {
    
    this.settings = settings;
    return this;
  }

   /**
   * Get settings
   * @return settings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SystemStatusSettings getSettings() {
    return settings;
  }


  public void setSettings(SystemStatusSettings settings) {
    this.settings = settings;
  }


  public SystemStatus security(SystemStatusSecurity security) {
    
    this.security = security;
    return this;
  }

   /**
   * Get security
   * @return security
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SystemStatusSecurity getSecurity() {
    return security;
  }


  public void setSecurity(SystemStatusSecurity security) {
    this.security = security;
  }


  public SystemStatus pages(List<String> pages) {
    
    this.pages = pages;
    return this;
  }

  public SystemStatus addPagesItem(String pagesItem) {
    if (this.pages == null) {
      this.pages = new ArrayList<String>();
    }
    this.pages.add(pagesItem);
    return this;
  }

   /**
   * WooCommerce pages.
   * @return pages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "WooCommerce pages.")

  public List<String> getPages() {
    return pages;
  }


  public void setPages(List<String> pages) {
    this.pages = pages;
  }


  public SystemStatus postTypeCounts(List<String> postTypeCounts) {
    
    this.postTypeCounts = postTypeCounts;
    return this;
  }

  public SystemStatus addPostTypeCountsItem(String postTypeCountsItem) {
    if (this.postTypeCounts == null) {
      this.postTypeCounts = new ArrayList<String>();
    }
    this.postTypeCounts.add(postTypeCountsItem);
    return this;
  }

   /**
   * Total post count.
   * @return postTypeCounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total post count.")

  public List<String> getPostTypeCounts() {
    return postTypeCounts;
  }


  public void setPostTypeCounts(List<String> postTypeCounts) {
    this.postTypeCounts = postTypeCounts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemStatus systemStatus = (SystemStatus) o;
    return Objects.equals(this.environment, systemStatus.environment) &&
        Objects.equals(this.database, systemStatus.database) &&
        Objects.equals(this.activePlugins, systemStatus.activePlugins) &&
        Objects.equals(this.inactivePlugins, systemStatus.inactivePlugins) &&
        Objects.equals(this.dropinsMuPlugins, systemStatus.dropinsMuPlugins) &&
        Objects.equals(this.theme, systemStatus.theme) &&
        Objects.equals(this.settings, systemStatus.settings) &&
        Objects.equals(this.security, systemStatus.security) &&
        Objects.equals(this.pages, systemStatus.pages) &&
        Objects.equals(this.postTypeCounts, systemStatus.postTypeCounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(environment, database, activePlugins, inactivePlugins, dropinsMuPlugins, theme, settings, security, pages, postTypeCounts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemStatus {\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    database: ").append(toIndentedString(database)).append("\n");
    sb.append("    activePlugins: ").append(toIndentedString(activePlugins)).append("\n");
    sb.append("    inactivePlugins: ").append(toIndentedString(inactivePlugins)).append("\n");
    sb.append("    dropinsMuPlugins: ").append(toIndentedString(dropinsMuPlugins)).append("\n");
    sb.append("    theme: ").append(toIndentedString(theme)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("    security: ").append(toIndentedString(security)).append("\n");
    sb.append("    pages: ").append(toIndentedString(pages)).append("\n");
    sb.append("    postTypeCounts: ").append(toIndentedString(postTypeCounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

