/**
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class CustomerDownload (
  /* Download ID. */
  downloadId: Option[String] = None,
  /* Download file URL. */
  downloadUrl: Option[String] = None,
  /* Downloadable product ID. */
  productId: Option[Int] = None,
  /* Product name. */
  productName: Option[String] = None,
  /* Downloadable file name. */
  downloadName: Option[String] = None,
  /* Order ID. */
  orderId: Option[Int] = None,
  /* Order key. */
  orderKey: Option[String] = None,
  /* Number of downloads remaining. */
  downloadsRemaining: Option[String] = None,
  /* The date when download access expires, in the site's timezone. */
  accessExpires: Option[String] = None,
  /* The date when download access expires, as GMT. */
  accessExpiresGmt: Option[String] = None,
  file: Option[CustomerDownloadFile] = None
) extends ApiModel

