/**
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class OrdersShippingLines (
  /* Item ID. */
  id: Option[Int] = None,
  /* Shipping method name. */
  methodTitle: Option[String] = None,
  /* Shipping method ID. */
  methodId: Option[String] = None,
  /* Shipping instance ID. */
  instanceId: Option[String] = None,
  /* Line total (after discounts). */
  total: Option[String] = None,
  /* Line total tax (after discounts). */
  totalTax: Option[String] = None,
  /* Line taxes. */
  taxes: Option[Seq[OrdersTaxes1]] = None,
  /* Meta data. */
  metaData: Option[Seq[CouponsMetaData]] = None
) extends ApiModel

