/**
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class PaymentGateway (
  /* Payment gateway ID. */
  id: Option[String] = None,
  /* Payment gateway title on checkout. */
  title: Option[String] = None,
  /* Payment gateway description on checkout. */
  description: Option[String] = None,
  /* Payment gateway sort order. */
  order: Option[Int] = None,
  /* Payment gateway enabled status. */
  enabled: Option[Boolean] = None,
  /* Payment gateway method title. */
  methodTitle: Option[String] = None,
  /* Payment gateway method description. */
  methodDescription: Option[String] = None,
  /* Supported features for this payment gateway. */
  methodSupports: Option[Seq[String]] = None,
  settings: Option[PaymentGatewaysIdSettings] = None
) extends ApiModel

