/**
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class ProductReview3 (
  /* Unique identifier for the product that the review belongs to. */
  productId: Option[Int] = None,
  /* Status of the review. */
  status: Option[ProductReview3Enums.Status] = None,
  /* Reviewer name. */
  reviewer: Option[String] = None,
  /* Reviewer email. */
  reviewerEmail: Option[String] = None,
  /* The content of the review. */
  review: Option[String] = None,
  /* Review rating (0 to 5). */
  rating: Option[Int] = None
) extends ApiModel

object ProductReview3Enums {

  type Status = Status.Value
  object Status extends Enumeration {
    val Approved = Value("approved")
    val Hold = Value("hold")
    val Spam = Value("spam")
    val Unspam = Value("unspam")
    val Trash = Value("trash")
    val Untrash = Value("untrash")
  }

}
