/**
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import org.woocommerce.akkaclient.core.ApiModel

case class ShopOrderRefundLineItems (
  /* Item ID. */
  id: Option[Int] = None,
  /* Product name. */
  name: Option[String] = None,
  /* Product ID. */
  productId: Option[String] = None,
  /* Variation ID, if applicable. */
  variationId: Option[Int] = None,
  /* Quantity ordered. */
  quantity: Option[Int] = None,
  /* Tax class of product. */
  taxClass: Option[String] = None,
  /* Line subtotal (before discounts). */
  subtotal: Option[String] = None,
  /* Line subtotal tax (before discounts). */
  subtotalTax: Option[String] = None,
  /* Line total (after discounts). */
  total: Option[String] = None,
  /* Line total tax (after discounts). */
  totalTax: Option[String] = None,
  /* Line taxes. */
  taxes: Option[Seq[ShopOrderRefundTaxes]] = None,
  /* Meta data. */
  metaData: Option[Seq[CouponsMetaData]] = None,
  /* Product SKU. */
  sku: Option[String] = None,
  /* Product price. */
  price: Option[BigDecimal] = None,
  /* Amount that will be refunded for this line item (excluding taxes). */
  refundTotal: Option[BigDecimal] = None
) extends ApiModel

