/**
 * wc/v3
 * OpenAPI documented, based on generated OpenAPI document of the namespace wc/v3 with some manual fixes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.woocommerce.akkaclient.model

import java.net.URI
import org.woocommerce.akkaclient.core.ApiModel

case class Webhook (
  /* Unique identifier for the resource. */
  id: Option[Int] = None,
  /* A friendly name for the webhook. */
  name: Option[String] = None,
  /* Webhook status. */
  status: Option[WebhookEnums.Status] = None,
  /* Webhook topic. */
  topic: Option[String] = None,
  /* Webhook resource. */
  resource: Option[String] = None,
  /* Webhook event. */
  event: Option[String] = None,
  /* WooCommerce action names associated with the webhook. */
  hooks: Option[Seq[String]] = None,
  /* The URL where the webhook payload is delivered. */
  deliveryUrl: Option[URI] = None,
  /* Secret key used to generate a hash of the delivered webhook and provided in the request headers. This will default to a MD5 hash from the current user's ID|username if not provided. */
  secret: Option[String] = None,
  /* The date the webhook was created, in the site's timezone. */
  dateCreated: Option[String] = None,
  /* The date the webhook was created, as GMT. */
  dateCreatedGmt: Option[String] = None,
  /* The date the webhook was last modified, in the site's timezone. */
  dateModified: Option[String] = None,
  /* The date the webhook was last modified, as GMT. */
  dateModifiedGmt: Option[String] = None
) extends ApiModel

object WebhookEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val Active = Value("active")
    val Paused = Value("paused")
    val Disabled = Value("disabled")
  }

}
